### ISSUE TITLE
Crash accessing results of FindAll("span")

### ISSUE THREAD

**Issue by andreygursky** [anaskhan96/soup#20]
```go
package main

import (
        "fmt"
        "github.com/anaskhan96/soup"
        "os"
)

func main() {
        resp, err := soup.Get("https://slashdot.com")
        if err != nil {
                os.Exit(1)
        }
        doc := soup.HTMLParse(resp)
        spans := doc.FindAll("span")
        for _, span := range spans {
                fmt.Println(span.Text())
        }
}
```
Result:
```
$ ./test-span
Slashdot
Stories
Polls
Deals
 Login
 Sign up
RSS
Facebook
Google+
Twitter
Newsletter
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x61aad7]

goroutine 1 [running]:
github.com/anaskhan96/soup.Root.Text(0xc420439030, 0x6bbff4, 0x4, 0x0, 0x0, 0x0, 0xa)
	go/src/github.com/anaskhan96/soup/soup.go:257 +0xa7
main.main()
	test-span.go:17 +0x1dd
```

**Comment by anaskhan96** [comment]
Fixed by #19
