### ISSUE TITLE
fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by weaming** [anaskhan96/soup#66]
```
fatal error: concurrent map iteration and map write

goroutine 833 [running]:
runtime.throw(0x7161cb, 0x26)
        /root/.gvm/gos/go1.15.5/src/runtime/panic.go:1116 +0x72 fp=0xc000069938 sp=0xc000069908 pc=0x437312
runtime.mapiternext(0xc000069a10)
        /root/.gvm/gos/go1.15.5/src/runtime/map.go:853 +0x554 fp=0xc0000699b8 sp=0xc000069938 pc=0x412574 
github.com/anaskhan96/soup.setHeadersAndCookies(0xc0002e4600)
        /root/go/pkg/mod/github.com/anaskhan96/soup@v1.2.4/soup.go:145 +0x87 fp=0xc000069b28 sp=0xc0000699b8 pc=0x6831a7
github.com/anaskhan96/soup.GetWithClient(0xc000288660, 0x24, 0xc0004b3da0, 0x0, 0x0, 0x0, 0x0)
        /root/go/pkg/mod/github.com/anaskhan96/soup@v1.2.4/soup.go:117 +0x18b fp=0xc000069be0 sp=0xc000069b28 pc=0x682cab
```

**Comment by pointone-tww** [comment]
use lock before setHeader
